// ═══ 千问 API 生成的国内城市数据（2026-03-24）═══
// 共 29 个城市

  {
    id: 'guangzhou', name: '广州', nameEn: 'Guangzhou',
    pinyin: 'guangzhou', pinyinAbbr: 'gz', pinyinInitial: 'G',
    country: '广东', countryPinyin: 'gu', countryPinyinInitial: 'G', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 82,
    image: 'https://images.unsplash.com/photo-1583996120517-3c7811c35ced?w=800&h=600&fit=crop',
    description: '千年商都，早茶烟火气与珠江夜韵交织',
    avgDailyBudget: 550, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['早茶', '粤菜', '珠江', '岭南'],
    lat: 23.1291, lng: 113.2644,
  },
  {
    id: 'shenzhen', name: '深圳', nameEn: 'Shenzhen',
    pinyin: 'shenzhen', pinyinAbbr: 'sz', pinyinInitial: 'S',
    country: '广东', countryPinyin: 'sh', countryPinyinInitial: 'S', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 81,
    image: 'https://images.unsplash.com/photo-1533464268036-5331b3fba110?w=800&h=600&fit=crop',
    description: '先锋都市森林，科技与滨海生态共生之地',
    avgDailyBudget: 680, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['科技', '滨海', '设计', '年轻'],
    lat: 22.5431, lng: 114.0579,
  },
  {
    id: 'tianjin', name: '天津', nameEn: 'Tianjin',
    pinyin: 'tianjin', pinyinAbbr: 'tj', pinyinInitial: 'T',
    country: '天津', countryPinyin: 'ti', countryPinyinInitial: 'T', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 79,
    image: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&h=600&fit=crop',
    description: '曲艺码头，海河蜿蜒处的中西建筑交响',
    avgDailyBudget: 420, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['相声', '海河', '洋楼', '小吃'],
    lat: 39.0842, lng: 117.1993,
  },
  {
    id: 'ningbo', name: '宁波', nameEn: 'Ningbo',
    pinyin: 'ningbo', pinyinAbbr: 'nb', pinyinInitial: 'N',
    country: '浙江', countryPinyin: 'ni', countryPinyinInitial: 'N', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 77,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '书藏古今，港通天下，江南儒商精神原乡',
    avgDailyBudget: 460, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['藏书楼', '港口', '浙东', '海鲜'],
    lat: 29.8683, lng: 121.544,
  },
  {
    id: 'quanzhou', name: '泉州', nameEn: 'Quanzhou',
    pinyin: 'quanzhou', pinyinAbbr: 'qz', pinyinInitial: 'Q',
    country: '福建', countryPinyin: 'qu', countryPinyinInitial: 'Q', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 75,
    image: 'https://images.unsplash.com/photo-1580197557722-77c1a7b08d33?w=800&h=600&fit=crop',
    description: '宋元中国的世界海洋商贸中心，半城烟火半城神',
    avgDailyBudget: 380, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['世遗', '海丝', '闽南', '古寺'],
    lat: 24.8915, lng: 118.6735,
  },
  {
    id: 'luoyang', name: '洛阳', nameEn: 'Luoyang',
    pinyin: 'luoyang', pinyinAbbr: 'ly', pinyinInitial: 'L',
    country: '河南', countryPinyin: 'lu', countryPinyinInitial: 'L', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 74,
    image: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800&h=600&fit=crop',
    description: '十三朝古都，牡丹灼灼，龙门石窟静默千年',
    avgDailyBudget: 400, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['牡丹', '石窟', '古都', '汉服'],
    lat: 34.6634, lng: 112.4342,
  },
  {
    id: 'kaifeng', name: '开封', nameEn: 'Kaifeng',
    pinyin: 'kaifeng', pinyinAbbr: 'kf', pinyinInitial: 'K',
    country: '河南', countryPinyin: 'ka', countryPinyinInitial: 'K', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 73,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '东京梦华录里的汴京风雅，一城宋韵半城水',
    avgDailyBudget: 360, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['宋文化', '包公', '清明上河图', '夜市'],
    lat: 34.7923, lng: 114.3019,
  },
  {
    id: 'wuzhen', name: '乌镇', nameEn: 'Wuzhen',
    pinyin: 'wuzhen', pinyinAbbr: 'wz', pinyinInitial: 'W',
    country: '浙江', countryPinyin: 'wu', countryPinyinInitial: 'W', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 72,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '水墨江南活标本，枕水人家与戏剧节共呼吸',
    avgDailyBudget: 580, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['水乡', '戏剧', '民宿', '慢生活'],
    lat: 30.8475, lng: 120.5429,
  },
  {
    id: 'yangshuo', name: '阳朔', nameEn: 'Yangshuo',
    pinyin: 'yangshuo', pinyinAbbr: 'ys', pinyinInitial: 'Y',
    country: '广西', countryPinyin: 'ya', countryPinyinInitial: 'Y', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 71,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '喀斯特山水画廊，骑行遇峰林，漓江泛轻舟',
    avgDailyBudget: 440, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['山水', '骑行', '攀岩', '西街'],
    lat: 25.2502, lng: 110.2825,
  },
  {
    id: 'beihai', name: '北海', nameEn: 'Beihai',
    pinyin: 'beihai', pinyinAbbr: 'bh', pinyinInitial: 'B',
    country: '广西', countryPinyin: 'be', countryPinyinInitial: 'B', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 70,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '北部湾明珠，银滩绵延，老街骑楼诉说百年海事',
    avgDailyBudget: 410, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['银滩', '老街', '海岛', '海鲜'],
    lat: 21.4837, lng: 109.1149,
  },
  {
    id: 'wuzhou', name: '梧州', nameEn: 'Wuzhou',
    pinyin: 'wuzhou', pinyinAbbr: 'wz', pinyinInitial: 'W',
    country: '广西', countryPinyin: 'wu', countryPinyinInitial: 'W', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 69,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '岭南古城，三江汇流处的骑楼茶香与粤剧余韵',
    avgDailyBudget: 330, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['骑楼', '六堡茶', '粤语', '三江'],
    lat: 23.4789, lng: 111.2747,
  },
  {
    id: 'jiuzaigou', name: '九寨沟', nameEn: 'Jiuzhaigou',
    pinyin: 'jiuzaigou', pinyinAbbr: 'jzg', pinyinInitial: 'J',
    country: '四川', countryPinyin: 'ji', countryPinyinInitial: 'J', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 68,
    image: 'https://images.unsplash.com/photo-1513415564515-763d91423bdd?w=800&h=600&fit=crop',
    description: '童话世界，翠海叠瀑与藏寨经幡共绘人间秘境',
    avgDailyBudget: 620, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['彩池', '藏族', '秋色', '徒步'],
    lat: 33.2192, lng: 103.8267,
  },
  {
    id: 'langmusi', name: '郎木寺', nameEn: 'Langmusi',
    pinyin: 'langmusi', pinyinAbbr: 'lms', pinyinInitial: 'L',
    country: '甘肃', countryPinyin: 'la', countryPinyinInitial: 'L', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 67,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '白龙江源头的藏地圣境，寺院金顶映雪域苍穹',
    avgDailyBudget: 470, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['藏传佛教', '草原', '峡谷', '转经'],
    lat: 34.0003, lng: 102.835,
  },
  {
    id: 'xingcheng', name: '兴城', nameEn: 'Xingcheng',
    pinyin: 'xingcheng', pinyinAbbr: 'xc', pinyinInitial: 'X',
    country: '辽宁', countryPinyin: 'xi', countryPinyinInitial: 'X', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 66,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '明代古城遗珠，海滨城墙与菊花岛共守辽东湾',
    avgDailyBudget: 390, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['古城', '海滨', '明长城', '海鲜'],
    lat: 40.6249, lng: 120.7224,
  },
  {
    id: 'ergun', name: '额尔古纳', nameEn: 'Ergun',
    pinyin: 'ergun', pinyinAbbr: 'egn', pinyinInitial: 'E',
    country: '内蒙古', countryPinyin: 'er', countryPinyinInitial: 'E', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 65,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '中俄边境额尔古纳河畔，草原林海与俄罗斯风情交融',
    avgDailyBudget: 510, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['草原', '界河', '白桦', '俄式'],
    lat: 49.2112, lng: 119.4721,
  },
  {
    id: 'hulunbuir', name: '呼伦贝尔', nameEn: 'Hulunbuir',
    pinyin: 'hulunbuir', pinyinAbbr: 'hlbe', pinyinInitial: 'H',
    country: '内蒙古', countryPinyin: 'hu', countryPinyinInitial: 'H', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 64,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '天下第一草原，莫日格勒河弯成蓝色哈达',
    avgDailyBudget: 560, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['草原', '牧民', '敖包', '星空'],
    lat: 49.1926, lng: 119.7444,
  },
  {
    id: 'xianggelila', name: '香格里拉', nameEn: 'Shangri-La',
    pinyin: 'xianggelila', pinyinAbbr: 'xgll', pinyinInitial: 'X',
    country: '云南', countryPinyin: 'xi', countryPinyinInitial: 'X', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 63,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '滇西北秘境，松赞林寺金顶辉映普达措高原湖泊',
    avgDailyBudget: 490, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['藏区', '高原', '寺庙', '湖泊'],
    lat: 27.8123, lng: 99.7048,
  },
  {
    id: 'xishuangbanna', name: '西双版纳', nameEn: 'Xishuangbanna',
    pinyin: 'xishuangbanna', pinyinAbbr: 'xsbn', pinyinInitial: 'X',
    country: '云南', countryPinyin: 'xi', countryPinyinInitial: 'X', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 62,
    image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&h=600&fit=crop',
    description: '北纬21°热带雨林，傣家竹楼与泼水节狂欢不息',
    avgDailyBudget: 450, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['雨林', '傣族', '泼水节', '野象'],
    lat: 22.0005, lng: 100.7942,
  },
  {
    id: 'wuzhishan', name: '五指山', nameEn: 'Wuzhishan',
    pinyin: 'wuzhishan', pinyinAbbr: 'wzs', pinyinInitial: 'W',
    country: '海南', countryPinyin: 'wu', countryPinyinInitial: 'W', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 61,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '海南之心，热带雨林腹地，黎苗文化原生地',
    avgDailyBudget: 430, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['雨林', '黎族', '登山', '瀑布'],
    lat: 18.7777, lng: 109.5195,
  },
  {
    id: 'weizhoudao', name: '涠洲岛', nameEn: 'Weizhou Island',
    pinyin: 'weizhoudao', pinyinAbbr: 'wzd', pinyinInitial: 'W',
    country: '广西', countryPinyin: 'we', countryPinyinInitial: 'W', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 60,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '火山海岛秘境，蓝眼泪与珊瑚屋在北部湾心跳',
    avgDailyBudget: 530, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['火山', '海岛', '潜水', '灯塔'],
    lat: 21.0998, lng: 109.1241,
  },
  {
    id: 'yantai', name: '烟台', nameEn: 'Yantai',
    pinyin: 'yantai', pinyinAbbr: 'yt', pinyinInitial: 'Y',
    country: '山东', countryPinyin: 'ya', countryPinyinInitial: 'Y', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 59,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '仙境海岸，蓬莱阁下葡萄美酒与渔火共长天',
    avgDailyBudget: 440, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['葡萄酒', '仙境', '海滨', '海鲜'],
    lat: 37.4722, lng: 121.4402,
  },
  {
    id: 'qinhuangdao', name: '秦皇岛', nameEn: 'Qinhuangdao',
    pinyin: 'qinhuangdao', pinyinAbbr: 'qhd', pinyinInitial: 'Q',
    country: '河北', countryPinyin: 'qi', countryPinyinInitial: 'Q', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 58,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '长城入海处，阿那亚与鸽子窝共守渤海之滨',
    avgDailyBudget: 570, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['长城', '阿那亚', '观鸟', '海滨'],
    lat: 39.9342, lng: 119.5843,
  },
  {
    id: 'anhui', name: '宏村', nameEn: 'Hongcun',
    pinyin: 'hongcun', pinyinAbbr: 'hc', pinyinInitial: 'H',
    country: '安徽', countryPinyin: 'ho', countryPinyinInitial: 'H', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 57,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '画里乡村，南湖月沼倒映马头墙徽派水墨',
    avgDailyBudget: 420, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['徽派', '古村', '摄影', '水墨'],
    lat: 29.8775, lng: 117.9737,
  },
  {
    id: 'pingyao', name: '平遥', nameEn: 'Pingyao',
    pinyin: 'pingyao', pinyinAbbr: 'py', pinyinInitial: 'P',
    country: '山西', countryPinyin: 'pi', countryPinyinInitial: 'P', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 56,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '活着的明清古城，票号风云与青砖巷陌未褪色',
    avgDailyBudget: 370, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['古城', '晋商', '票号', '城墙'],
    lat: 37.1907, lng: 112.172,
  },
  {
    id: 'dandong', name: '丹东', nameEn: 'Dandong',
    pinyin: 'dandong', pinyinAbbr: 'dd', pinyinInitial: 'D',
    country: '辽宁', countryPinyin: 'da', countryPinyinInitial: 'D', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 55,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '鸭绿江畔国门之城，断桥夕照与朝鲜风情一线牵',
    avgDailyBudget: 350, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['边境', '鸭绿江', '断桥', '朝鲜'],
    lat: 40.1292, lng: 124.3741,
  },
  {
    id: 'yichang', name: '宜昌', nameEn: 'Yichang',
    pinyin: 'yichang', pinyinAbbr: 'yc', pinyinInitial: 'Y',
    country: '湖北', countryPinyin: 'yi', countryPinyinInitial: 'Y', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 54,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '三峡门户，屈原故里，高峡平湖与清江画廊并秀',
    avgDailyBudget: 400, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['三峡', '屈原', '水电', '清江'],
    lat: 30.6988, lng: 111.282,
  },
  {
    id: 'zhuhai', name: '珠海', nameEn: 'Zhuhai',
    pinyin: 'zhuhai', pinyinAbbr: 'zh', pinyinInitial: 'Z',
    country: '广东', countryPinyin: 'zh', countryPinyinInitial: 'Z', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 53,
    image: 'https://images.unsplash.com/photo-1559628233-100c798642d4?w=800&h=600&fit=crop',
    description: '百岛之城，情侣路海风拂面，港珠澳大桥飞虹跨海',
    avgDailyBudget: 520, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['海岛', '情侣路', '大桥', '澳门'],
    lat: 22.2708, lng: 113.5569,
  },
  {
    id: 'lanzhou', name: '兰州', nameEn: 'Lanzhou',
    pinyin: 'lanzhou', pinyinAbbr: 'lz', pinyinInitial: 'L',
    country: '甘肃', countryPinyin: 'la', countryPinyinInitial: 'L', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 52,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '黄河穿城而过，一碗牛肉面热腾着丝路千年烟火',
    avgDailyBudget: 380, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['黄河', '牛肉面', '丝路', '清真'],
    lat: 36.0611, lng: 103.8343,
  },
  {
    id: 'zhangye', name: '张掖', nameEn: 'Zhangye',
    pinyin: 'zhangye', pinyinAbbr: 'zy', pinyinInitial: 'Z',
    country: '甘肃', countryPinyin: 'zh', countryPinyinInitial: 'Z', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 51,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '七彩丹霞燃尽祁连山麓，马蹄寺悬于千仞绝壁',
    avgDailyBudget: 460, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['丹霞', '祁连山', '石窟', '河西走廊'],
    lat: 38.9222, lng: 100.4503,
  },