// ═══ 千问 API 批量生成数据（2026-03-24）═══
// 国内新增 19 个，国际新增 80 个

// ──── 国内城市 ────
  {
    id: 'jilin', name: '吉林市', nameEn: 'Jilin City',
    pinyin: 'jilin', pinyinAbbr: 'jl', pinyinInitial: 'J',
    country: '吉林', countryPinyin: 'jilin', countryPinyinInitial: 'J', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 69,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '雾凇之都，松花江畔银装世界（25字以内）',
    avgDailyBudget: 380, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['雾凇', '松花江', '滑雪', '北国'],
    lat: 43.8362, lng: 126.5561,
  },
  {
    id: 'shenyang', name: '沈阳', nameEn: 'Shenyang',
    pinyin: 'shenyang', pinyinAbbr: 'sy', pinyinInitial: 'S',
    country: '辽宁', countryPinyin: 'liaoning', countryPinyinInitial: 'L', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 65,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '盛京遗韵，故宫钟鼓回响千年（25字以内）',
    avgDailyBudget: 360, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['清宫', '工业', '东北菜', '历史'],
    lat: 41.7921, lng: 123.4326,
  },
  {
    id: 'changchun', name: '长春', nameEn: 'Changchun',
    pinyin: 'changchun', pinyinAbbr: 'cc', pinyinInitial: 'C',
    country: '吉林', countryPinyin: 'jilin', countryPinyinInitial: 'J', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 64,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '林荫春城，伪满遗迹与电影摇篮（25字以内）',
    avgDailyBudget: 350, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['电影', '伪满', '森林', '汽车'],
    lat: 43.8171, lng: 125.3235,
  },
  {
    id: 'xuzhou', name: '徐州', nameEn: 'Xuzhou',
    pinyin: 'xuzhou', pinyinAbbr: 'xz', pinyinInitial: 'X',
    country: '江苏', countryPinyin: 'jiangsu', countryPinyinInitial: 'J', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 63,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '五省通衢，汉高故里楚韵悠长（25字以内）',
    avgDailyBudget: 340, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['汉文化', '战争史', '彭祖', '两汉'],
    lat: 34.2616, lng: 117.1846,
  },
  {
    id: 'nanchang', name: '南昌', nameEn: 'Nanchang',
    pinyin: 'nanchang', pinyinAbbr: 'nc', pinyinInitial: 'N',
    country: '江西', countryPinyin: 'jiangxi', countryPinyinInitial: 'J', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 60,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '英雄城头，滕王阁外赣江潮涌（25字以内）',
    avgDailyBudget: 330, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['红色', '滕王阁', '赣江', '海昏侯'],
    lat: 28.6765, lng: 115.8922,
  },
  {
    id: 'shaoxing', name: '绍兴', nameEn: 'Shaoxing',
    pinyin: 'shaoxing', pinyinAbbr: 'sx', pinyinInitial: 'S',
    country: '浙江', countryPinyin: 'zhejiang', countryPinyinInitial: 'Z', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 59,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '水乡墨韵，鲁迅故里黄酒飘香（25字以内）',
    avgDailyBudget: 370, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['水乡', '黄酒', '鲁迅', '乌篷船'],
    lat: 30.0442, lng: 120.5849,
  },
  {
    id: 'jingdezhen', name: '景德镇', nameEn: 'Jingdezhen',
    pinyin: 'jingdezhen', pinyinAbbr: 'jdz', pinyinInitial: 'J',
    country: '江西', countryPinyin: 'jiangxi', countryPinyinInitial: 'J', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 58,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '千年瓷都，高岭土烧出青花梦（25字以内）',
    avgDailyBudget: 380, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['陶瓷', '古窑', '手作', '非遗'],
    lat: 29.2924, lng: 117.2165,
  },
  {
    id: 'tongli', name: '同里', nameEn: 'Tongli',
    pinyin: 'tongli', pinyinAbbr: 'tl', pinyinInitial: 'T',
    country: '江苏', countryPinyin: 'jiangsu', countryPinyinInitial: 'J', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 57,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '东方小威尼斯，退思园里水墨江南（25字以内）',
    avgDailyBudget: 410, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['古镇', '园林', '小桥', '慢生活'],
    lat: 31.1598, lng: 120.7257,
  },
  {
    id: 'zhengzhou', name: '郑州', nameEn: 'Zhengzhou',
    pinyin: 'zhengzhou', pinyinAbbr: 'zz', pinyinInitial: 'Z',
    country: '河南', countryPinyin: 'henan', countryPinyinInitial: 'H', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 56,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '天地之中，商都遗址青铜回响（25字以内）',
    avgDailyBudget: 320, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['商都', '嵩山', '少林', '中原'],
    lat: 34.7466, lng: 113.6254,
  },
  {
    id: 'hohhot', name: '呼和浩特', nameEn: 'Hohhot',
    pinyin: 'hohhot', pinyinAbbr: 'hhht', pinyinInitial: 'H',
    country: '内蒙古', countryPinyin: 'neimenggu', countryPinyinInitial: 'N', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 54,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '青城草原，大召寺金顶映白云（25字以内）',
    avgDailyBudget: 370, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['草原', '召庙', '蒙古族', '奶食'],
    lat: 40.8185, lng: 111.6707,
  },
  {
    id: 'xining', name: '西宁', nameEn: 'Xining',
    pinyin: 'xining', pinyinAbbr: 'xn', pinyinInitial: 'X',
    country: '青海', countryPinyin: 'qinghai', countryPinyinInitial: 'Q', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 53,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '夏都西陲，塔尔寺酥油花绽雪域（25字以内）',
    avgDailyBudget: 360, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['青藏门户', '藏传佛教', '清真', '高原'],
    lat: 36.6232, lng: 101.7777,
  },
  {
    id: 'yinchuan', name: '银川', nameEn: 'Yinchuan',
    pinyin: 'yinchuan', pinyinAbbr: 'yc', pinyinInitial: 'Y',
    country: '宁夏', countryPinyin: 'ningxia', countryPinyinInitial: 'N', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 52,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '塞上江南，贺兰山下西夏王陵静默（25字以内）',
    avgDailyBudget: 350, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['西夏', '黄河', '贺兰山', '枸杞'],
    lat: 38.4831, lng: 106.2713,
  },
  {
    id: 'wulumuqi', name: '乌鲁木齐', nameEn: 'Urumqi',
    pinyin: 'wulumuqi', pinyinAbbr: 'wlmq', pinyinInitial: 'W',
    country: '新疆', countryPinyin: 'xinjiang', countryPinyinInitial: 'X', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 51,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '亚心之都，大巴扎烟火烤馕飘香（25字以内）',
    avgDailyBudget: 420, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['亚心', '大巴扎', '天山', '维吾尔'],
    lat: 43.8257, lng: 87.6173,
  },
  {
    id: 'jiujiang', name: '九江', nameEn: 'Jiujiang',
    pinyin: 'jiujiang', pinyinAbbr: 'jj', pinyinInitial: 'J',
    country: '江西', countryPinyin: 'jiangxi', countryPinyinInitial: 'J', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 48,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '浔阳江头，庐山云雾茶香漫山（25字以内）',
    avgDailyBudget: 340, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['庐山', '长江', '白鹿洞', '茶乡'],
    lat: 29.7139, lng: 115.9825,
  },
  {
    id: 'yibin', name: '宜宾', nameEn: 'Yibin',
    pinyin: 'yibin', pinyinAbbr: 'yb', pinyinInitial: 'Y',
    country: '四川', countryPinyin: 'sichuan', countryPinyinInitial: 'S', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 47,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '万里长江第一城，五粮液香醉三江口（25字以内）',
    avgDailyBudget: 360, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['长江', '白酒', '蜀南竹海', '李庄'],
    lat: 28.758, lng: 104.6332,
  },
  {
    id: 'baotou', name: '包头', nameEn: 'Baotou',
    pinyin: 'baotou', pinyinAbbr: 'bt', pinyinInitial: 'B',
    country: '内蒙古', countryPinyin: 'neimenggu', countryPinyinInitial: 'N', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 45,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '稀土之都，赛汗塔拉草原城中绿肺（25字以内）',
    avgDailyBudget: 330, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['稀土', '草原', '黄河', '军工'],
    lat: 40.6564, lng: 109.8417,
  },
  {
    id: 'qufu', name: '曲阜', nameEn: 'Qufu',
    pinyin: 'qufu', pinyinAbbr: 'qf', pinyinInitial: 'Q',
    country: '山东', countryPinyin: 'shandong', countryPinyinInitial: 'S', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 44,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '东方圣城，孔庙杏坛礼乐悠扬（25字以内）',
    avgDailyBudget: 320, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['孔子', '三孔', '儒家', '古建'],
    lat: 35.5923, lng: 116.9925,
  },
  {
    id: 'hefei', name: '合肥', nameEn: 'Hefei',
    pinyin: 'hefei', pinyinAbbr: 'hf', pinyinInitial: 'H',
    country: '安徽', countryPinyin: 'anhui', countryPinyinInitial: 'A', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 42,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '江淮首郡，巢湖烟波包公故里（25字以内）',
    avgDailyBudget: 310, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['科教', '巢湖', '包公', '徽菜'],
    lat: 31.8206, lng: 117.2272,
  },
  {
    id: 'lishan', name: '丽山', nameEn: 'Lishan',
    pinyin: 'lishan', pinyinAbbr: 'ls', pinyinInitial: 'L',
    country: '台湾', countryPinyin: 'taiwan', countryPinyinInitial: 'T', countryFlag: '🇨🇳',
    isDomestic: true, hotness: 78,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '日月潭畔雾霭轻，邵族歌谣绕青山（25字以内）',
    avgDailyBudget: 500, currency: 'CNY', timezone: 'Asia/Shanghai',
    tags: ['日月潭', '阿里山', '邵族文化', '红茶'],
    lat: 23.8728, lng: 120.8927,
  },

// ──── 国际城市 ────
  {
    id: 'hongkong', name: '香港', nameEn: 'Hong Kong',
    pinyin: 'xianggang', pinyinAbbr: 'xg', pinyinInitial: 'X',
    country: '中国', countryPinyin: 'zhongguo', countryPinyinInitial: 'Z', countryFlag: '🇨🇳',
    isDomestic: false, hotness: 98,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '维港夜色霓虹海风，山海城共舞（25字以内）',
    avgDailyBudget: 850, currency: 'CNY', timezone: 'Asia/Tokyo',
    tags: ['都市', '美食', '购物', '海港'],
    lat: 22.3193, lng: 114.1694,
  },
  {
    id: 'taipei', name: '台北', nameEn: 'Taipei',
    pinyin: 'taibei', pinyinAbbr: 'tb', pinyinInitial: 'T',
    country: '中国', countryPinyin: 'zhongguo', countryPinyinInitial: 'Z', countryFlag: '🇨🇳',
    isDomestic: false, hotness: 95,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '九份山城茶香氤氲，夜市烟火不眠（25字以内）',
    avgDailyBudget: 600, currency: 'CNY', timezone: 'Asia/Tokyo',
    tags: ['古城', '夜市', '茶文化', '文艺'],
    lat: 25.032, lng: 121.5654,
  },
  {
    id: 'luangprabang', name: '琅勃拉邦', nameEn: 'Luang Prabang',
    pinyin: 'langbolabang', pinyinAbbr: 'lblb', pinyinInitial: 'L',
    country: '老挝', countryPinyin: 'laowo', countryPinyinInitial: 'L', countryFlag: '🇱🇦',
    isDomestic: false, hotness: 89,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '湄公河畔千佛静默，晨光布施如诗流淌（25字以内）',
    avgDailyBudget: 420, currency: 'CNY', timezone: 'Asia/Bangkok',
    tags: ['古城', '佛教', '河流', '慢生活'],
    lat: 19.8975, lng: 102.1278,
  },
  {
    id: 'siemreap', name: '暹粒', nameEn: 'Siem Reap',
    pinyin: 'xianli', pinyinAbbr: 'xl', pinyinInitial: 'X',
    country: '柬埔寨', countryPinyin: 'jianpuzhai', countryPinyinInitial: 'J', countryFlag: '🇰🇭',
    isDomestic: false, hotness: 88,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '吴哥微笑千年守望，丛林古寺光影斑驳（25字以内）',
    avgDailyBudget: 450, currency: 'CNY', timezone: 'Asia/Bangkok',
    tags: ['古迹', '丛林', '摄影', '佛教'],
    lat: 13.3622, lng: 103.8599,
  },
  {
    id: 'colombo', name: '科伦坡', nameEn: 'Colombo',
    pinyin: 'kelunpo', pinyinAbbr: 'klp', pinyinInitial: 'K',
    country: '斯里兰卡', countryPinyin: 'sililanka', countryPinyinInitial: 'S', countryFlag: '🇱🇰',
    isDomestic: false, hotness: 86,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '印度洋畔殖民风街巷，香料市集热浪翻涌（25字以内）',
    avgDailyBudget: 400, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['港口', '殖民建筑', '香料', '多元文化'],
    lat: 6.9271, lng: 79.8612,
  },
  {
    id: 'kathmandu', name: '加德满都', nameEn: 'Kathmandu',
    pinyin: 'jiademandu', pinyinAbbr: 'jdmdu', pinyinInitial: 'J',
    country: '尼泊尔', countryPinyin: 'niboer', countryPinyinInitial: 'N', countryFlag: '🇳🇵',
    isDomestic: false, hotness: 85,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '雪山环抱的神庙之城，转经筒声绕云端（25字以内）',
    avgDailyBudget: 380, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['宗教', '雪山', '手工艺', '徒步起点'],
    lat: 27.7172, lng: 85.324,
  },
  {
    id: 'vientiane', name: '万象', nameEn: 'Vientiane',
    pinyin: 'wanxiang', pinyinAbbr: 'wx', pinyinInitial: 'W',
    country: '老挝', countryPinyin: 'laowo', countryPinyinInitial: 'L', countryFlag: '🇱🇦',
    isDomestic: false, hotness: 84,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '湄公河畔法式慵懒，金色塔銮映霞光（25字以内）',
    avgDailyBudget: 430, currency: 'CNY', timezone: 'Asia/Bangkok',
    tags: ['首都', '法式风情', '佛教', '河景'],
    lat: 17.9678, lng: 102.6033,
  },
  {
    id: 'yangon', name: '仰光', nameEn: 'Yangon',
    pinyin: 'yangguang', pinyinAbbr: 'yg', pinyinInitial: 'Y',
    country: '缅甸', countryPinyin: 'miandian', countryPinyinInitial: 'M', countryFlag: '🇲🇲',
    isDomestic: false, hotness: 83,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '大金塔金光刺破晨雾，殖民街巷时光凝滞（25字以内）',
    avgDailyBudget: 460, currency: 'CNY', timezone: 'Asia/Bangkok',
    tags: ['佛塔', '殖民建筑', '历史', '市井'],
    lat: 16.8409, lng: 96.1735,
  },
  {
    id: 'hochiminhcity', name: '胡志明市', nameEn: 'Ho Chi Minh City',
    pinyin: 'huzhimingshi', pinyinAbbr: 'hzms', pinyinInitial: 'H',
    country: '越南', countryPinyin: 'yuenan', countryPinyinInitial: 'Y', countryFlag: '🇻🇳',
    isDomestic: false, hotness: 82,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '西贡旧梦咖啡香浓，法越混血街巷生辉（25字以内）',
    avgDailyBudget: 480, currency: 'CNY', timezone: 'Asia/Bangkok',
    tags: ['都市', '法式建筑', '咖啡', '战争遗迹'],
    lat: 10.7703, lng: 106.7017,
  },
  {
    id: 'hanoi', name: '河内', nameEn: 'Hanoi',
    pinyin: 'henoi', pinyinAbbr: 'hn', pinyinInitial: 'H',
    country: '越南', countryPinyin: 'yuenan', countryPinyinInitial: 'Y', countryFlag: '🇻🇳',
    isDomestic: false, hotness: 80,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '还剑湖畔法越交融，三十六行街烟火人间（25字以内）',
    avgDailyBudget: 470, currency: 'CNY', timezone: 'Asia/Tokyo',
    tags: ['古城', '湖泊', '法式', '小吃'],
    lat: 21.0278, lng: 105.8342,
  },
  {
    id: 'cagayan', name: '卡加延', nameEn: 'Cagayan de Oro',
    pinyin: 'kajiayan', pinyinAbbr: 'kjy', pinyinInitial: 'K',
    country: '菲律宾', countryPinyin: 'feilvbin', countryPinyinInitial: 'F', countryFlag: '🇵🇭',
    isDomestic: false, hotness: 79,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '白水漂流激荡山野，棉兰老岛秘境心跳（25字以内）',
    avgDailyBudget: 410, currency: 'CNY', timezone: 'UTC',
    tags: ['漂流', '自然', '冒险', '小众'],
    lat: 8.4775, lng: 124.8422,
  },
  {
    id: 'boracay', name: '长滩岛', nameEn: 'Boracay',
    pinyin: 'changtan dao', pinyinAbbr: 'ctd', pinyinInitial: 'C',
    country: '菲律宾', countryPinyin: 'feilvbin', countryPinyinInitial: 'F', countryFlag: '🇵🇭',
    isDomestic: false, hotness: 78,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '白沙滩细如面粉，落日帆影醉染碧海（25字以内）',
    avgDailyBudget: 650, currency: 'CNY', timezone: 'UTC',
    tags: ['海岛', '白沙', '日落', '水上活动'],
    lat: 11.9885, lng: 121.9203,
  },
  {
    id: 'chittagong', name: '吉大港', nameEn: 'Chittagong',
    pinyin: 'jidagang', pinyinAbbr: 'jdg', pinyinInitial: 'J',
    country: '孟加拉国', countryPinyin: 'mengjialaguo', countryPinyinInitial: 'M', countryFlag: '🇧🇩',
    isDomestic: false, hotness: 77,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '孟加拉湾畔古老商港，清真寺穹顶映潮汐（25字以内）',
    avgDailyBudget: 350, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['港口', '伊斯兰', '殖民遗迹', '渔港'],
    lat: 22.3381, lng: 91.8218,
  },
  {
    id: 'jaipur', name: '斋浦尔', nameEn: 'Jaipur',
    pinyin: 'zhaiyuer', pinyinAbbr: 'zye', pinyinInitial: 'Z',
    country: '印度', countryPinyin: 'yindu', countryPinyinInitial: 'Y', countryFlag: '🇮🇳',
    isDomestic: false, hotness: 76,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '粉红之城宫墙低语，拉贾斯坦瑰丽梦境（25字以内）',
    avgDailyBudget: 390, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['古城', '宫殿', '色彩', '手工艺'],
    lat: 26.9124, lng: 75.7873,
  },
  {
    id: 'varanasi', name: '瓦拉纳西', nameEn: 'Varanasi',
    pinyin: 'walanaxi', pinyinAbbr: 'wlnx', pinyinInitial: 'W',
    country: '印度', countryPinyin: 'yindu', countryPinyinInitial: 'Y', countryFlag: '🇮🇳',
    isDomestic: false, hotness: 75,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '恒河晨浴圣火不熄，千年梵音萦绕石阶（25字以内）',
    avgDailyBudget: 360, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['宗教圣地', '恒河', '朝圣', '古老'],
    lat: 25.3167, lng: 83.0122,
  },
  {
    id: 'kandy', name: '康提', nameEn: 'Kandy',
    pinyin: 'kangti', pinyinAbbr: 'kt', pinyinInitial: 'K',
    country: '斯里兰卡', countryPinyin: 'sililanka', countryPinyinInitial: 'S', countryFlag: '🇱🇰',
    isDomestic: false, hotness: 74,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '圣牙寺藏佛牙舍利，山间湖城云雾缭绕（25字以内）',
    avgDailyBudget: 370, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['佛教', '湖泊', '山地', '文化'],
    lat: 7.2906, lng: 80.6337,
  },
  {
    id: 'baguio', name: '碧瑶', nameEn: 'Baguio',
    pinyin: 'biyao', pinyinAbbr: 'by', pinyinInitial: 'B',
    country: '菲律宾', countryPinyin: 'feilvbin', countryPinyinInitial: 'F', countryFlag: '🇵🇭',
    isDomestic: false, hotness: 73,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '菲律宾‘夏都’松林环绕，美式山城遗韵悠长（25字以内）',
    avgDailyBudget: 440, currency: 'CNY', timezone: 'UTC',
    tags: ['山城', '避暑', '松林', '美式遗产'],
    lat: 16.4221, lng: 120.5939,
  },
  {
    id: 'sapporo', name: '札幌', nameEn: 'Sapporo',
    pinyin: 'zhahu', pinyinAbbr: 'zh', pinyinInitial: 'Z',
    country: '日本', countryPinyin: 'riben', countryPinyinInitial: 'R', countryFlag: '🇯🇵',
    isDomestic: false, hotness: 72,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '北海道雪国之心，味噌拉面暖冬夜（25字以内）',
    avgDailyBudget: 760, currency: 'CNY', timezone: 'Asia/Tokyo',
    tags: ['都市', '冰雪节', '美食', '滑雪'],
    lat: 43.0618, lng: 141.3545,
  },
  {
    id: 'nagoya', name: '名古屋', nameEn: 'Nagoya',
    pinyin: 'mingguwu', pinyinAbbr: 'mgw', pinyinInitial: 'M',
    country: '日本', countryPinyin: 'riben', countryPinyinInitial: 'R', countryFlag: '🇯🇵',
    isDomestic: false, hotness: 69,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '中部工业重镇藏匠心，热田神宫诉战国风云（25字以内）',
    avgDailyBudget: 700, currency: 'CNY', timezone: 'Asia/Tokyo',
    tags: ['工业', '历史', '美食', '交通枢纽'],
    lat: 35.1815, lng: 136.9066,
  },
  {
    id: 'fukuoka', name: '福冈', nameEn: 'Fukuoka',
    pinyin: 'fugang', pinyinAbbr: 'fg', pinyinInitial: 'F',
    country: '日本', countryPinyin: 'riben', countryPinyinInitial: 'R', countryFlag: '🇯🇵',
    isDomestic: false, hotness: 68,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '博多拉面香飘九州，太宰府梅雨润千年（25字以内）',
    avgDailyBudget: 690, currency: 'CNY', timezone: 'Asia/Tokyo',
    tags: ['美食', '九州', '神社', '港口'],
    lat: 33.5904, lng: 130.4017,
  },
  {
    id: 'busan', name: '釜山', nameEn: 'Busan',
    pinyin: 'fushan', pinyinAbbr: 'fs', pinyinInitial: 'F',
    country: '韩国', countryPinyin: 'hanguo', countryPinyinInitial: 'H', countryFlag: '🇰🇷',
    isDomestic: false, hotness: 67,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '韩国最大海港，海云台浪花撞碎夕阳（25字以内）',
    avgDailyBudget: 660, currency: 'CNY', timezone: 'Asia/Tokyo',
    tags: ['海滨', '港口', '温泉', '电影'],
    lat: 35.1796, lng: 129.0756,
  },
  {
    id: 'macau', name: '澳门', nameEn: 'Macau',
    pinyin: 'aomen', pinyinAbbr: 'am', pinyinInitial: 'A',
    country: '中国', countryPinyin: 'zhongguo', countryPinyinInitial: 'Z', countryFlag: '🇨🇳',
    isDomestic: false, hotness: 65,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '葡韵老城光影斑驳，妈阁庙香火绵延四百年（25字以内）',
    avgDailyBudget: 820, currency: 'CNY', timezone: 'Asia/Tokyo',
    tags: ['博彩', '中西合璧', '历史', '美食'],
    lat: 22.1987, lng: 113.5439,
  },
  {
    id: 'penang', name: '槟城', nameEn: 'Penang',
    pinyin: 'bingcheng', pinyinAbbr: 'bc', pinyinInitial: 'B',
    country: '马来西亚', countryPinyin: 'malaixiya', countryPinyinInitial: 'M', countryFlag: '🇲🇾',
    isDomestic: false, hotness: 64,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '乔治市涂鸦巷弄生趣，娘惹糕甜入南洋旧梦（25字以内）',
    avgDailyBudget: 500, currency: 'CNY', timezone: 'Asia/Bangkok',
    tags: ['古城', '美食', '殖民', '文化'],
    lat: 5.4149, lng: 100.3292,
  },
  {
    id: 'hualien', name: '花莲', nameEn: 'Hualien',
    pinyin: 'hualien', pinyinAbbr: 'hl', pinyinInitial: 'H',
    country: '中国', countryPinyin: 'zhongguo', countryPinyinInitial: 'Z', countryFlag: '🇨🇳',
    isDomestic: false, hotness: 63,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '太平洋岸断崖惊涛，太鲁阁峡谷翡翠奔流（25字以内）',
    avgDailyBudget: 630, currency: 'CNY', timezone: 'Asia/Tokyo',
    tags: ['峡谷', '海岸', '原住民', '自然'],
    lat: 23.9739, lng: 121.6081,
  },
  {
    id: 'newyork', name: '纽约', nameEn: 'New York',
    pinyin: 'niuyue', pinyinAbbr: 'ny', pinyinInitial: 'N',
    country: '美国', countryPinyin: 'meiguo', countryPinyinInitial: 'M', countryFlag: '🇺🇸',
    isDomestic: false, hotness: 95,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '时代广场霓虹不眠，自由女神守望梦想（24字）',
    avgDailyBudget: 1200, currency: 'CNY', timezone: 'America/New_York',
    tags: ['摩天楼', '百老汇', '博物馆', '多元文化'],
    lat: 40.7128, lng: -74.006,
  },
  {
    id: 'amsterdam', name: '阿姆斯特丹', nameEn: 'Amsterdam',
    pinyin: 'anmudan', pinyinAbbr: 'amd', pinyinInitial: 'A',
    country: '荷兰', countryPinyin: 'helan', countryPinyinInitial: 'H', countryFlag: '🇳🇱',
    isDomestic: false, hotness: 91,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '运河如诗蜿蜒，郁金香与梵高在风中低语（24字）',
    avgDailyBudget: 900, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['运河', '博物馆', '自行车', '艺术'],
    lat: 52.3676, lng: 4.9041,
  },
  {
    id: 'prague', name: '布拉格', nameEn: 'Prague',
    pinyin: 'bulage', pinyinAbbr: 'blg', pinyinInitial: 'B',
    country: '捷克', countryPinyin: 'jieke', countryPinyinInitial: 'J', countryFlag: '🇨🇿',
    isDomestic: false, hotness: 89,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '查理大桥晨雾未散，童话城堡静立伏尔塔瓦河（25字）',
    avgDailyBudget: 650, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['古堡', '查理桥', '天文钟', '啤酒'],
    lat: 50.0755, lng: 14.4378,
  },
  {
    id: 'lisbon', name: '里斯本', nameEn: 'Lisbon',
    pinyin: 'lisiben', pinyinAbbr: 'lsb', pinyinInitial: 'L',
    country: '葡萄牙', countryPinyin: 'putaoya', countryPinyinInitial: 'P', countryFlag: '🇵🇹',
    isDomestic: false, hotness: 87,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '电车爬坡穿七丘，大西洋落日熔金入海（23字）',
    avgDailyBudget: 720, currency: 'CNY', timezone: 'Europe/London',
    tags: ['电车', '海港', '瓷砖画', '法多音乐'],
    lat: 38.7223, lng: -9.1393,
  },
  {
    id: 'vienna', name: '维也纳', nameEn: 'Vienna',
    pinyin: 'weiyena', pinyinAbbr: 'wyn', pinyinInitial: 'W',
    country: '奥地利', countryPinyin: 'aodili', countryPinyinInitial: 'A', countryFlag: '🇦🇹',
    isDomestic: false, hotness: 86,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '金色大厅音符未落，美泉宫玫瑰正盛（22字）',
    avgDailyBudget: 880, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['古典音乐', '宫殿', '咖啡馆', '华尔兹'],
    lat: 48.2082, lng: 16.3738,
  },
  {
    id: 'berlin', name: '柏林', nameEn: 'Berlin',
    pinyin: 'bolin', pinyinAbbr: 'bl', pinyinInitial: 'B',
    country: '德国', countryPinyin: 'deguo', countryPinyinInitial: 'D', countryFlag: '🇩🇪',
    isDomestic: false, hotness: 85,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '柏林墙涂鸦鲜活，博物馆岛沉淀千年回响（23字）',
    avgDailyBudget: 820, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['历史遗迹', '街头艺术', '设计', '夜生活'],
    lat: 52.52, lng: 13.405,
  },
  {
    id: 'reykjavik', name: '雷克雅未克', nameEn: 'Reykjavik',
    pinyin: 'leikeyaweike', pinyinAbbr: 'lkwyk', pinyinInitial: 'L',
    country: '冰岛', countryPinyin: 'bingdao', countryPinyinInitial: 'B', countryFlag: '🇮🇸',
    isDomestic: false, hotness: 84,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '极光掠过火山口，蓝湖蒸汽氤氲北欧冬夜（24字）',
    avgDailyBudget: 1300, currency: 'CNY', timezone: 'UTC',
    tags: ['极光', '温泉', '火山', '极昼极夜'],
    lat: 64.1466, lng: -21.9426,
  },
  {
    id: 'copenhaguen', name: '哥本哈根', nameEn: 'Copenhagen',
    pinyin: 'gebenhagen', pinyinAbbr: 'gbhg', pinyinInitial: 'G',
    country: '丹麦', countryPinyin: 'danmai', countryPinyinInitial: 'D', countryFlag: '🇩🇰',
    isDomestic: false, hotness: 83,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '小美人鱼静望海港，新港彩屋倒映碧波（22字）',
    avgDailyBudget: 950, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['童话', '设计', '自行车', '港口'],
    lat: 55.6761, lng: 12.5683,
  },
  {
    id: 'zurich', name: '苏黎世', nameEn: 'Zurich',
    pinyin: 'sulishi', pinyinAbbr: 'sls', pinyinInitial: 'S',
    country: '瑞士', countryPinyin: 'ruishi', countryPinyinInitial: 'R', countryFlag: '🇨🇭',
    isDomestic: false, hotness: 82,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '利马特河穿城而过，雪山为幕咖啡飘香（22字）',
    avgDailyBudget: 1100, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['金融中心', '湖泊', '雪山', '巧克力'],
    lat: 47.3769, lng: 8.5417,
  },
  {
    id: 'dubrovnik', name: '杜布罗夫尼克', nameEn: 'Dubrovnik',
    pinyin: 'duboluowenik', pinyinAbbr: 'dblwnk', pinyinInitial: 'D',
    country: '克罗地亚', countryPinyin: 'keluodiya', countryPinyinInitial: 'K', countryFlag: '🇭🇷',
    isDomestic: false, hotness: 81,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '城墙环抱亚得里亚海，红瓦白墙如中世纪明信片（25字）',
    avgDailyBudget: 780, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['古城墙', '海景', ' Game of Thrones', '石板路'],
    lat: 42.6507, lng: 18.0944,
  },
  {
    id: 'budapest', name: '布达佩斯', nameEn: 'Budapest',
    pinyin: 'budaipesi', pinyinAbbr: 'bdps', pinyinInitial: 'B',
    country: '匈牙利', countryPinyin: 'xiongyali', countryPinyinInitial: 'X', countryFlag: '🇭🇺',
    isDomestic: false, hotness: 80,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '多瑙河畔双城辉映，链子桥灯火点亮千年（24字）',
    avgDailyBudget: 620, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['温泉浴场', '国会大厦', '多瑙河', '城堡山'],
    lat: 47.4979, lng: 19.0402,
  },
  {
    id: 'quebec', name: '魁北克市', nameEn: 'Quebec City',
    pinyin: 'kuibeikeye', pinyinAbbr: 'kbky', pinyinInitial: 'K',
    country: '加拿大', countryPinyin: 'jianada', countryPinyinInitial: 'J', countryFlag: '🇨🇦',
    isDomestic: false, hotness: 79,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '北美最古老法语城，芳堤娜城堡守望圣劳伦斯（25字）',
    avgDailyBudget: 800, currency: 'CNY', timezone: 'America/New_York',
    tags: ['法语文化', '古城墙', '冬季嘉年华', '枫糖'],
    lat: 46.8139, lng: -71.208,
  },
  {
    id: 'vancouver', name: '温哥华', nameEn: 'Vancouver',
    pinyin: 'wengehua', pinyinAbbr: 'wgh', pinyinInitial: 'W',
    country: '加拿大', countryPinyin: 'jianada', countryPinyinInitial: 'J', countryFlag: '🇨🇦',
    isDomestic: false, hotness: 78,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '雪山入城，斯坦利公园海风拂面四季皆宜（23字）',
    avgDailyBudget: 920, currency: 'CNY', timezone: 'America/Los_Angeles',
    tags: ['自然城市', '太平洋', '滑雪', '多元移民'],
    lat: 49.2827, lng: -123.1207,
  },
  {
    id: 'mexicocity', name: '墨西哥城', nameEn: 'Mexico City',
    pinyin: 'moxigecheng', pinyinAbbr: 'mxgc', pinyinInitial: 'M',
    country: '墨西哥', countryPinyin: 'moxige', countryPinyinInitial: 'M', countryFlag: '🇲🇽',
    isDomestic: false, hotness: 77,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '阿兹特克遗址之上，壁画与美食共舞千年（23字）',
    avgDailyBudget: 550, currency: 'CNY', timezone: 'America/New_York',
    tags: ['古文明', '壁画', '辣椒美食', '高原湖城'],
    lat: 19.4326, lng: -99.1332,
  },
  {
    id: 'cancun', name: '坎昆', nameEn: 'Cancun',
    pinyin: 'kanqun', pinyinAbbr: 'kq', pinyinInitial: 'K',
    country: '墨西哥', countryPinyin: 'moxige', countryPinyinInitial: 'M', countryFlag: '🇲🇽',
    isDomestic: false, hotness: 76,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '加勒比蔚蓝泻湖，玛雅丛林掩映白色沙滩（23字）',
    avgDailyBudget: 700, currency: 'CNY', timezone: 'America/New_York',
    tags: ['海岛度假', '玛雅遗址', '潜水', '夜生活'],
    lat: 21.1619, lng: -86.8515,
  },
  {
    id: 'lima', name: '利马', nameEn: 'Lima',
    pinyin: 'lima', pinyinAbbr: 'lm', pinyinInitial: 'L',
    country: '秘鲁', countryPinyin: 'milu', countryPinyinInitial: 'M', countryFlag: '🇵🇪',
    isDomestic: false, hotness: 75,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '太平洋畔殖民明珠，悬崖边品一杯皮斯科酸（24字）',
    avgDailyBudget: 480, currency: 'CNY', timezone: 'America/New_York',
    tags: ['殖民建筑', '美食之都', '悬崖海景', '秘鲁菜'],
    lat: -12.0464, lng: -77.0428,
  },
  {
    id: 'cusco', name: '库斯科', nameEn: 'Cusco',
    pinyin: 'kuskou', pinyinAbbr: 'ksk', pinyinInitial: 'K',
    country: '秘鲁', countryPinyin: 'milu', countryPinyinInitial: 'M', countryFlag: '🇵🇪',
    isDomestic: false, hotness: 74,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '印加帝国心脏，石墙无声诉说安第斯荣光（23字）',
    avgDailyBudget: 420, currency: 'CNY', timezone: 'America/New_York',
    tags: ['印加遗址', '高原', '圣谷', '传统纺织'],
    lat: -13.5164, lng: -71.9774,
  },
  {
    id: 'santiago', name: '圣地亚哥', nameEn: 'Santiago',
    pinyin: 'shengdiya ge', pinyinAbbr: 'sdyg', pinyinInitial: 'S',
    country: '智利', countryPinyin: 'zhili', countryPinyinInitial: 'Z', countryFlag: '🇨🇱',
    isDomestic: false, hotness: 73,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '安第斯雪峰作背景，中央山谷红酒微醺（23字）',
    avgDailyBudget: 600, currency: 'CNY', timezone: 'America/New_York',
    tags: ['雪山', '葡萄酒', '殖民广场', '铜矿文化'],
    lat: -33.4484, lng: -70.6693,
  },
  {
    id: 'valparaiso', name: '瓦尔帕莱索', nameEn: 'Valparaiso',
    pinyin: 'waerpalaisuo', pinyinAbbr: 'welps', pinyinInitial: 'W',
    country: '智利', countryPinyin: 'zhili', countryPinyinInitial: 'Z', countryFlag: '🇨🇱',
    isDomestic: false, hotness: 72,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '彩色山城攀陡坡，太平洋浪花吻上百年电梯（25字）',
    avgDailyBudget: 520, currency: 'CNY', timezone: 'America/New_York',
    tags: ['彩色建筑', '港口', '街头涂鸦', '诗人故居'],
    lat: -33.0458, lng: -71.6197,
  },
  {
    id: 'buenosaires', name: '布宜诺斯艾利斯', nameEn: 'Buenos Aires',
    pinyin: 'buyinosailisi', pinyinAbbr: 'bnsls', pinyinInitial: 'B',
    country: '阿根廷', countryPinyin: 'argentina', countryPinyinInitial: 'A', countryFlag: '🇦🇷',
    isDomestic: false, hotness: 71,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '探戈在博卡区街角旋转，五月广场鸽群飞过（24字）',
    avgDailyBudget: 580, currency: 'CNY', timezone: 'UTC',
    tags: ['探戈', '欧式建筑', '牛肉', '文学'],
    lat: -34.6037, lng: -58.3816,
  },
  {
    id: 'rio', name: '里约热内卢', nameEn: 'Rio de Janeiro',
    pinyin: 'liyuoreneilu', pinyinAbbr: 'lyrnl', pinyinInitial: 'L',
    country: '巴西', countryPinyin: 'baxi', countryPinyinInitial: 'B', countryFlag: '🇧🇷',
    isDomestic: false, hotness: 70,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '基督像俯瞰海湾，科帕卡巴纳沙滩永不落幕（24字）',
    avgDailyBudget: 650, currency: 'CNY', timezone: 'UTC',
    tags: ['海滩', '基督像', '狂欢节', '山海之城'],
    lat: -22.9068, lng: -43.1729,
  },
  {
    id: 'salvador', name: '萨尔瓦多', nameEn: 'Salvador',
    pinyin: 'saerwaduo', pinyinAbbr: 'sewd', pinyinInitial: 'S',
    country: '巴西', countryPinyin: 'baxi', countryPinyinInitial: 'B', countryFlag: '🇧🇷',
    isDomestic: false, hotness: 69,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '巴西首个首都，葡式彩墙沿悬崖跌入大西洋（25字）',
    avgDailyBudget: 460, currency: 'CNY', timezone: 'UTC',
    tags: ['殖民遗产', '非洲文化', '悬崖教堂', '海鲜'],
    lat: -12.9714, lng: -38.5111,
  },
  {
    id: 'tromso', name: '特罗姆瑟', nameEn: 'Tromso',
    pinyin: 'teluomshe', pinyinAbbr: 'tlms', pinyinInitial: 'T',
    country: '挪威', countryPinyin: 'nuowei', countryPinyinInitial: 'N', countryFlag: '🇳🇴',
    isDomestic: false, hotness: 68,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '北极圈内不夜城，极光猎人集结的玻璃屋营地（25字）',
    avgDailyBudget: 1400, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['极光', '北极圈', '峡湾', '萨米文化'],
    lat: 69.6492, lng: 18.9553,
  },
  {
    id: 'stockholm', name: '斯德哥尔摩', nameEn: 'Stockholm',
    pinyin: 'sidedegeomu', pinyinAbbr: 'sdgem', pinyinInitial: 'S',
    country: '瑞典', countryPinyin: 'ruidian', countryPinyinInitial: 'R', countryFlag: '🇸🇪',
    isDomestic: false, hotness: 67,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '水道穿城如丝带，老城鹅卵石路通向维京传说（25字）',
    avgDailyBudget: 980, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['水上城市', '老城', '设计', '诺贝尔奖'],
    lat: 59.3293, lng: 18.0686,
  },
  {
    id: 'helsinki', name: '赫尔辛基', nameEn: 'Helsinki',
    pinyin: 'erxinsiji', pinyinAbbr: 'exsj', pinyinInitial: 'E',
    country: '芬兰', countryPinyin: 'fenlan', countryPinyinInitial: 'F', countryFlag: '🇫🇮',
    isDomestic: false, hotness: 66,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '白夜漫游设计之都，海港教堂静听波罗的海潮（25字）',
    avgDailyBudget: 930, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['设计', '海港', '桑拿', '白夜'],
    lat: 60.1699, lng: 24.9384,
  },
  {
    id: 'krakow', name: '克拉科夫', nameEn: 'Krakow',
    pinyin: 'kelakefu', pinyinAbbr: 'klkf', pinyinInitial: 'K',
    country: '波兰', countryPinyin: 'bolan', countryPinyinInitial: 'B', countryFlag: '🇵🇱',
    isDomestic: false, hotness: 65,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '欧洲最古老大学城，瓦维尔城堡见证千年王冠（25字）',
    avgDailyBudget: 500, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['中世纪老城', '犹太区', '盐矿', '学术氛围'],
    lat: 50.0647, lng: 19.945,
  },
  {
    id: 'edmonton', name: '埃德蒙顿', nameEn: 'Edmonton',
    pinyin: 'aidemendun', pinyinAbbr: 'adem', pinyinInitial: 'A',
    country: '加拿大', countryPinyin: 'jianada', countryPinyinInitial: 'J', countryFlag: '🇨🇦',
    isDomestic: false, hotness: 64,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '北方门户之城，西埃德蒙顿商城与河谷步道共生（25字）',
    avgDailyBudget: 760, currency: 'CNY', timezone: 'America/New_York',
    tags: ['河谷公园', '冬季活动', '原住民文化', '石油城'],
    lat: 53.5461, lng: -113.4938,
  },
  {
    id: 'halifax', name: '哈利法克斯', nameEn: 'Halifax',
    pinyin: 'halifaxi', pinyinAbbr: 'hlfx', pinyinInitial: 'H',
    country: '加拿大', countryPinyin: 'jianada', countryPinyinInitial: 'J', countryFlag: '🇨🇦',
    isDomestic: false, hotness: 63,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '大西洋畔军港城，灯塔守望帆影，龙虾鲜甜正当时（25字）',
    avgDailyBudget: 740, currency: 'CNY', timezone: 'America/New_York',
    tags: ['海港', '灯塔', '龙虾', '英伦风情'],
    lat: 44.6488, lng: -63.5752,
  },
  {
    id: 'santafe', name: '圣菲', nameEn: 'Santa Fe',
    pinyin: 'shengfei', pinyinAbbr: 'sf', pinyinInitial: 'S',
    country: '美国', countryPinyin: 'meiguo', countryPinyinInitial: 'M', countryFlag: '🇺🇸',
    isDomestic: false, hotness: 62,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '北美最古老州府，土坯建筑与沙漠阳光共绘新墨西哥（25字）',
    avgDailyBudget: 860, currency: 'CNY', timezone: 'America/New_York',
    tags: ['土坯建筑', '艺术村', '印第安文化', '沙漠景观'],
    lat: 35.687, lng: -105.9378,
  },
  {
    id: 'dubai', name: '迪拜', nameEn: 'Dubai',
    pinyin: 'dubi', pinyinAbbr: 'db', pinyinInitial: 'D',
    country: '阿联酋', countryPinyin: 'alianqiu', countryPinyinInitial: 'A', countryFlag: '🇦🇪',
    isDomestic: false, hotness: 96,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '沙漠奇迹之城，帆船酒店耀夜空',
    avgDailyBudget: 1200, currency: 'CNY', timezone: 'Asia/Dubai',
    tags: ['奢华', '沙漠', '购物', '摩天楼'],
    lat: 25.2769, lng: 55.2962,
  },
  {
    id: 'cairo', name: '开罗', nameEn: 'Cairo',
    pinyin: 'kailuo', pinyinAbbr: 'kl', pinyinInitial: 'K',
    country: '埃及', countryPinyin: 'ejí', countryPinyinInitial: 'E', countryFlag: '🇪🇬',
    isDomestic: false, hotness: 93,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '尼罗河畔金字塔，千年法老守晨光',
    avgDailyBudget: 480, currency: 'CNY', timezone: 'Europe/Istanbul',
    tags: ['金字塔', '博物馆', '古城', '尼罗河'],
    lat: 30.0444, lng: 31.2357,
  },
  {
    id: 'telaviv', name: '特拉维夫', nameEn: 'Tel Aviv',
    pinyin: 'telawei fu', pinyinAbbr: 'tlwf', pinyinInitial: 'T',
    country: '以色列', countryPinyin: 'yiselie', countryPinyinInitial: 'Y', countryFlag: '🇮🇱',
    isDomestic: false, hotness: 91,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '地中海蓝岸，白城包豪斯跃动青春',
    avgDailyBudget: 850, currency: 'CNY', timezone: 'Europe/Istanbul',
    tags: ['海滨', '设计', '夜生活', '历史'],
    lat: 32.0853, lng: 34.7818,
  },
  {
    id: 'istanbul', name: '伊斯坦布尔', nameEn: 'Istanbul',
    pinyin: 'yisitanbuer', pinyinAbbr: 'ystbe', pinyinInitial: 'Y',
    country: '土耳其', countryPinyin: 'tuerqi', countryPinyinInitial: 'T', countryFlag: '🇹🇷',
    isDomestic: false, hotness: 89,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '横跨欧亚的千年帝都，蓝色清真寺映晚霞',
    avgDailyBudget: 700, currency: 'CNY', timezone: 'Europe/Istanbul',
    tags: ['清真寺', '集市', '海峡', '美食'],
    lat: 41.0082, lng: 28.9784,
  },
  {
    id: 'antalya', name: '安塔利亚', nameEn: 'Antalya',
    pinyin: 'antaliya', pinyinAbbr: 'atly', pinyinInitial: 'A',
    country: '土耳其', countryPinyin: 'tuerqi', countryPinyinInitial: 'T', countryFlag: '🇹🇷',
    isDomestic: false, hotness: 87,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '地中海翡翠海岸，古罗马门迎海风',
    avgDailyBudget: 620, currency: 'CNY', timezone: 'Europe/Istanbul',
    tags: ['海滨', '古城', '悬崖', '温泉'],
    lat: 36.8969, lng: 30.7133,
  },
  {
    id: 'cape town', name: '开普敦', nameEn: 'Cape Town',
    pinyin: 'kaipudun', pinyinAbbr: 'kpd', pinyinInitial: 'K',
    country: '南非', countryPinyin: 'nanfei', countryPinyinInitial: 'N', countryFlag: '🇿🇦',
    isDomestic: false, hotness: 85,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '桌山云海间，好望角浪击天涯石',
    avgDailyBudget: 760, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['山海', '观景台', '葡萄酒', '野生动物'],
    lat: -33.9249, lng: 18.4241,
  },
  {
    id: 'marrakech', name: '马拉喀什', nameEn: 'Marrakech',
    pinyin: 'malakaishi', pinyinAbbr: 'mlks', pinyinInitial: 'M',
    country: '摩洛哥', countryPinyin: 'moluoge', countryPinyinInitial: 'M', countryFlag: '🇲🇦',
    isDomestic: false, hotness: 84,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '红墙迷宫市集，撒哈拉风拂玫瑰香',
    avgDailyBudget: 520, currency: 'CNY', timezone: 'Europe/London',
    tags: ['集市', '庭院', '沙漠', '手工艺'],
    lat: 31.6295, lng: -7.9811,
  },
  {
    id: 'nairobi', name: '内罗毕', nameEn: 'Nairobi',
    pinyin: 'neiluobi', pinyinAbbr: 'nlb', pinyinInitial: 'N',
    country: '肯尼亚', countryPinyin: 'keniya', countryPinyinInitial: 'K', countryFlag: '🇰🇪',
    isDomestic: false, hotness: 82,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '非洲之心跳动处，长颈鹿庄园共早餐',
    avgDailyBudget: 680, currency: 'CNY', timezone: 'Europe/Istanbul',
    tags: ['野生动物', '草原', '城市公园', '文化'],
    lat: -1.2864, lng: 36.8172,
  },
  {
    id: 'fiji', name: '斐济', nameEn: 'Fiji',
    pinyin: 'feiji', pinyinAbbr: 'fj', pinyinInitial: 'F',
    country: '斐济', countryPinyin: 'feiji', countryPinyinInitial: 'F', countryFlag: '🇫🇯',
    isDomestic: false, hotness: 81,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '南太平洋微笑之国，珊瑚环抱白沙眠',
    avgDailyBudget: 950, currency: 'CNY', timezone: 'Australia/Sydney',
    tags: ['海岛', '潜水', '度假村', '文化'],
    lat: -18.1439, lng: 178.431,
  },
  {
    id: 'auckland', name: '奥克兰', nameEn: 'Auckland',
    pinyin: 'aikelan', pinyinAbbr: 'akl', pinyinInitial: 'A',
    country: '新西兰', countryPinyin: 'xinxilan', countryPinyinInitial: 'X', countryFlag: '🇳🇿',
    isDomestic: false, hotness: 80,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '千帆之都枕火山湾，毛利纹样融现代街',
    avgDailyBudget: 820, currency: 'CNY', timezone: 'Australia/Sydney',
    tags: ['港口', '火山', '毛利文化', '美食'],
    lat: -36.8485, lng: 174.7633,
  },
  {
    id: 'queenstown', name: '皇后镇', nameEn: 'Queenstown',
    pinyin: 'huanghouzhen', pinyinAbbr: 'hqz', pinyinInitial: 'H',
    country: '新西兰', countryPinyin: 'xinxilan', countryPinyinInitial: 'X', countryFlag: '🇳🇿',
    isDomestic: false, hotness: 79,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '南岛心脏跳动地，雪山湖光冒险天堂',
    avgDailyBudget: 900, currency: 'CNY', timezone: 'Australia/Sydney',
    tags: ['湖泊', '雪山', '极限运动', '徒步'],
    lat: -45.0312, lng: 168.6626,
  },
  {
    id: 'tahiti', name: '大溪地', nameEn: 'Tahiti',
    pinyin: 'daxidi', pinyinAbbr: 'dxd', pinyinInitial: 'D',
    country: '法属波利尼西亚', countryPinyin: 'fashu bolinixiya', countryPinyinInitial: 'F', countryFlag: '🇵🇫',
    isDomestic: false, hotness: 78,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '波利尼西亚明珠，碧水浮屋听潮眠',
    avgDailyBudget: 1300, currency: 'CNY', timezone: 'America/Los_Angeles',
    tags: ['海岛', '水上屋', '泻湖', '文化'],
    lat: -17.651, lng: -149.4239,
  },
  {
    id: 'almaty', name: '阿拉木图', nameEn: 'Almaty',
    pinyin: 'alamu tu', pinyinAbbr: 'alt', pinyinInitial: 'A',
    country: '哈萨克斯坦', countryPinyin: 'hasakestan', countryPinyinInitial: 'H', countryFlag: '🇰🇿',
    isDomestic: false, hotness: 77,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '天山脚下的绿洲城，苏联遗韵混中亚风',
    avgDailyBudget: 420, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['山脉', '苏联建筑', '果园', '滑雪'],
    lat: 43.2389, lng: 76.8897,
  },
  {
    id: 'bishkek', name: '比什凯克', nameEn: 'Bishkek',
    pinyin: 'bishenke', pinyinAbbr: 'bsk', pinyinInitial: 'B',
    country: '吉尔吉斯斯坦', countryPinyin: 'jierjisisitan', countryPinyinInitial: 'J', countryFlag: '🇰🇬',
    isDomestic: false, hotness: 75,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '天山北麓静谧都，列宁广场飘雪与诗',
    avgDailyBudget: 380, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['广场', '山脉', '苏联遗迹', '市场'],
    lat: 42.8746, lng: 74.5698,
  },
  {
    id: 'tashkent', name: '塔什干', nameEn: 'Tashkent',
    pinyin: 'tashen', pinyinAbbr: 'ts', pinyinInitial: 'T',
    country: '乌兹别克斯坦', countryPinyin: 'wuzibiekesitan', countryPinyinInitial: 'W', countryFlag: '🇺🇿',
    isDomestic: false, hotness: 74,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '丝路明珠焕新生，蓝穹清真寺诉千年',
    avgDailyBudget: 450, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['古城', '清真寺', '地铁', '丝绸'],
    lat: 41.2995, lng: 69.2401,
  },
  {
    id: 'samarkand', name: '撒马尔罕', nameEn: 'Samarkand',
    pinyin: 'samaerhan', pinyinAbbr: 'smeh', pinyinInitial: 'S',
    country: '乌兹别克斯坦', countryPinyin: 'wuzibiekesitan', countryPinyinInitial: 'W', countryFlag: '🇺🇿',
    isDomestic: false, hotness: 73,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '帖木儿帝国金心，雷吉斯坦广场星穹耀',
    avgDailyBudget: 430, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['古城', '伊斯兰建筑', '天文台', '手工地毯'],
    lat: 39.6541, lng: 66.9743,
  },
  {
    id: 'port louis', name: '路易港', nameEn: 'Port Louis',
    pinyin: 'luyigang', pinyinAbbr: 'lyg', pinyinInitial: 'L',
    country: '毛里求斯', countryPinyin: 'maoliqu', countryPinyinInitial: 'M', countryFlag: '🇲🇺',
    isDomestic: false, hotness: 72,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '印度洋彩虹港，殖民老城撞糖田海风',
    avgDailyBudget: 880, currency: 'CNY', timezone: 'Asia/Dubai',
    tags: ['港口', '多元文化', '蔗田', '海港'],
    lat: -20.1619, lng: 57.4999,
  },
  {
    id: 'grand baie', name: '大湾', nameEn: 'Grand Baie',
    pinyin: 'dawan', pinyinAbbr: 'dw', pinyinInitial: 'D',
    country: '毛里求斯', countryPinyin: 'maoliqu', countryPinyinInitial: 'M', countryFlag: '🇲🇺',
    isDomestic: false, hotness: 71,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '毛里求斯派对湾，粉沙滩上落日微醺',
    avgDailyBudget: 920, currency: 'CNY', timezone: 'Asia/Dubai',
    tags: ['海滩', '夜生活', '游艇', '潜水'],
    lat: -20.0292, lng: 57.6372,
  },
  {
    id: 'petra', name: '佩特拉', nameEn: 'Petra',
    pinyin: 'peitrala', pinyinAbbr: 'ptl', pinyinInitial: 'P',
    country: '约旦', countryPinyin: 'yuedan', countryPinyinInitial: 'Y', countryFlag: '🇯🇴',
    isDomestic: false, hotness: 70,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '玫瑰古城凿岩中，西克峡谷光引秘境',
    avgDailyBudget: 560, currency: 'CNY', timezone: 'Europe/Istanbul',
    tags: ['古城', '峡谷', '岩石建筑', '考古'],
    lat: 30.3128, lng: 35.4729,
  },
  {
    id: 'amman', name: '安曼', nameEn: 'Amman',
    pinyin: 'anman', pinyinAbbr: 'am', pinyinInitial: 'A',
    country: '约旦', countryPinyin: 'yuedan', countryPinyinInitial: 'Y', countryFlag: '🇯🇴',
    isDomestic: false, hotness: 69,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '七丘之城叠古今，罗马剧场俯望橄榄山',
    avgDailyBudget: 490, currency: 'CNY', timezone: 'Europe/Istanbul',
    tags: ['古城', '罗马遗迹', '山顶城堡', '市场'],
    lat: 31.9539, lng: 35.9106,
  },
  {
    id: 'windhoek', name: '温得和克', nameEn: 'Windhoek',
    pinyin: 'wendeheke', pinyinAbbr: 'wdhk', pinyinInitial: 'W',
    country: '纳米比亚', countryPinyin: 'namibiya', countryPinyinInitial: 'N', countryFlag: '🇳🇦',
    isDomestic: false, hotness: 68,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '非洲高原德式城，独立纪念碑映赭石山',
    avgDailyBudget: 640, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['殖民建筑', '高原', '纪念碑', '自然'],
    lat: -22.5705, lng: 17.0834,
  },
  {
    id: 'zanzibar', name: '桑给巴尔', nameEn: 'Zanzibar',
    pinyin: 'sanggeibaer', pinyinAbbr: 'sgbe', pinyinInitial: 'S',
    country: '坦桑尼亚', countryPinyin: 'tansangniya', countryPinyinInitial: 'T', countryFlag: '🇹🇿',
    isDomestic: false, hotness: 67,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '香料群岛老城，石头城月光染珊瑚巷',
    avgDailyBudget: 720, currency: 'CNY', timezone: 'Europe/Istanbul',
    tags: ['古城', '香料', '海滩', '斯瓦希里文化'],
    lat: -6.165, lng: 39.1967,
  },
  {
    id: 'luanda', name: '罗安达', nameEn: 'Luanda',
    pinyin: 'luoan da', pinyinAbbr: 'lad', pinyinInitial: 'L',
    country: '安哥拉', countryPinyin: 'angela', countryPinyinInitial: 'A', countryFlag: '🇦🇴',
    isDomestic: false, hotness: 66,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '大西洋畔葡式都，殖民教堂守棕榈海岸',
    avgDailyBudget: 1100, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['海滨', '殖民建筑', '夜生活', '美食'],
    lat: -8.8382, lng: 13.2392,
  },
  {
    id: 'astana', name: '努尔苏丹', nameEn: 'Nur-Sultan',
    pinyin: 'nuer sudi an', pinyinAbbr: 'nsda', pinyinInitial: 'N',
    country: '哈萨克斯坦', countryPinyin: 'hasakestan', countryPinyinInitial: 'H', countryFlag: '🇰🇿',
    isDomestic: false, hotness: 65,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '未来主义草原都，可汗之帐穹顶耀星辰',
    avgDailyBudget: 460, currency: 'CNY', timezone: 'Asia/Kolkata',
    tags: ['现代建筑', '草原', '政治中心', '雕塑'],
    lat: 51.1694, lng: 71.4491,
  },
  {
    id: 'george town', name: '乔治市', nameEn: 'George Town',
    pinyin: 'qiaozhizhi', pinyinAbbr: 'qzz', pinyinInitial: 'Q',
    country: '马来西亚', countryPinyin: 'malaixiya', countryPinyinInitial: 'M', countryFlag: '🇲🇾',
    isDomestic: false, hotness: 64,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '槟城壁画小巷，娘惹瓷光映百年骑楼',
    avgDailyBudget: 390, currency: 'CNY', timezone: 'Asia/Bangkok',
    tags: ['壁画', '娘惹文化', '骑楼', '世界遗产'],
    lat: 5.4149, lng: 100.3292,
  },
  {
    id: 'valletta', name: '瓦莱塔', nameEn: 'Valletta',
    pinyin: 'waleita', pinyinAbbr: 'wlt', pinyinInitial: 'W',
    country: '马耳他', countryPinyin: 'maer_ta', countryPinyinInitial: 'M', countryFlag: '🇲🇹',
    isDomestic: false, hotness: 62,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '地中海骑士堡，巴洛克巷口望蓝洞天光',
    avgDailyBudget: 780, currency: 'CNY', timezone: 'Europe/Paris',
    tags: ['古城', '骑士团', '海港', '巴洛克'],
    lat: 35.8992, lng: 14.5141,
  },
  {
    id: 'la paz', name: '拉巴斯', nameEn: 'La Paz',
    pinyin: 'labasi', pinyinAbbr: 'lbs', pinyinInitial: 'L',
    country: '玻利维亚', countryPinyin: 'bolivya', countryPinyinInitial: 'B', countryFlag: '🇧🇴',
    isDomestic: false, hotness: 60,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: '世界最高首都，缆车穿云掠印加山谷',
    avgDailyBudget: 470, currency: 'CNY', timezone: 'America/New_York',
    tags: ['高原', '缆车', '印加文化', '市场'],
    lat: -16.5, lng: -68.15,
  },
